In [1]:
import numpy as np
arr=np.array([10,20,30,40,50])
print(arr)

[10 20 30 40 50]


In [5]:
# checking numpy version
import numpy as np
arr=np.array([10,20,30])

print(type(arr))

<class 'numpy.ndarray'>


In [6]:
#converting tuple into array

arr2=np.array((45,3,67,234,89))
print(arr2)
print(type(arr2))



[ 45   3  67 234  89]
<class 'numpy.ndarray'>


In [17]:
# 0D array
arr1=np.array(24)
print(arr1)
# 1D aray
arr2=np.array([10,20,30,40,50])
print(arr2)
# 2D aray
arr3=np.array([[10,20,30],[40,50,60]])
print(arr3)
# 3D aray
arr4=np.array([[[10,30,45,50],[18,56,89,60],[78,45,23,75]]])
print(arr4)


24
[10 20 30 40 50]
[[10 20 30]
 [40 50 60]]
[[[10 30 45 50]
  [18 56 89 60]
  [78 45 23 75]]]


In [15]:
#checking dimensions of array
arr4=np.array([[[10,30,45,50],[18,56,89,60],[78,45,23,75]]])
print(arr4.ndim)

3


In [3]:
#checking version of Numpy
import numpy as np
print(np.__version__)

2.3.0


In [7]:
# accessing element of array
arr1=np.array([12,13,14,15,16])
print(arr1[2])
arr2=np.array([[10,20,30,40],[23,45,67,89]])
print(arr2[1,2])
# OR we can access like this
print('2nd element of 2nd row',arr2[0,1])

14
67
2nd element of 2nd row 20


In [9]:
# negative indexing
arr2=np.array([[10,20,30,40],[23,45,67,89]])
print(arr2[1,-1])

89


In [15]:
# slicing in array
#positive slicing
arr=np.array([20,30,45,67,33,21,41])
print(arr[1:6:2])
# negavtive slicing
arr2=np.array([1,2,3,4,5,6,7,8,9,0])
print(arr2[])

[30 67 21]


In [21]:
#checking data type of array
arr=np.array([12,3,4,123,5,6,75])
print(arr.dtype)
arr1=np.array([1.2,34.7,12.89,9.34,7])
print(arr1.dtype)
arr2=np.array(['k','w','v','r','b','s'])
print(arr2.dtype)
arr3=np.array([23.45000,346.7890654,90.3456])
print(arr3.dtype)

int64
float64
<U1
float64


In [32]:
# shape of an array
arr=np.array([[12,13,12],[23,67,12],[78,98,67],[87,6,45]])
print(arr.shape)
# reshaping array
arr2=np.array([1,2,3,4,5,6,7,5,2,7,9,6])
newarr=arr2.reshape(3,4)
print(newarr)

(4, 3)
[[1 2 3 4]
 [5 6 7 5]
 [2 7 9 6]]


In [28]:
#size of an array
arr3=np.array([[12,13,12],[23,67,12],[78,98,67],[87,6,45]])
print(arr3.size)

12


In [35]:
# iterating array
arr=np.array([2,6,8,7,0,3])
for i in arr:
    print(i)

2
6
8
7
0
3


In [36]:
# joining array
#concanitating array
arr1=np.array([12,34,65,23])
arr2=np.array([45,23,43])
arr=np.concatenate((arr1,arr2))
print(arr)



[12 34 65 23 45 23 43]


In [44]:
# spliting array
arr2=np.array([1,2,3,4,5,6,7,5,2,7,9,6])
newarr=np.array_split(arr2,8)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 5]), array([2]), array([7]), array([9]), array([6])]
